services:
  react-prod:
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
    ports:
      - "8080:8080"

  react-dev:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    ports:
      - "5173:5173"
    develop:
      watch:
        - action: sync
          path: .
          target: /app

  react-test:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    command: [ "npm", "run", "test" ]
